### ISSUE TITLE
sample_plugin/README.md should be a sample, not a template

### ISSUE THREAD

**Issue by marcus7070** [CadQuery/cadquery-plugins#6]
If it's a sample then the README should probably contain actual installation and usage instructions, rather than be a template like it is now.

Honestly, I just want to copy and paste your installation instructions into my own plugin directory, @jmwright. :grin:

**Comment by jmwright** [comment]
Well, I'm not sure what the best way to install is. I had wondered if we should try to push these plugins to PyPi via CI so they can be installed with pip. Otherwise the user needs to clone the repo and copy the plugin to somewhere in PYTHONPATH. If we push to PyPi, maybe we should prefix all the plugin names with `cadquery_`. Thoughts?

**Comment by adam-urbanczyk** [comment]
It is not strictly needed to push to pypi to make it installable via pip - you can always install directly via git e.g. `pip install git+https://github.com/CadQuery/cadquery-plugins.git`

**Comment by jmwright** [comment]
But we have multiple plugins housed in the same repo. I would guess we can use [this technique](https://stackoverflow.com/a/19516714) thought? That sounds like it could be the way to go. I can add that to the sample repo's readme.

**Comment by jmwright** [comment]
I made [some progress](https://github.com/CadQuery/cadquery-plugins/tree/main/plugins/sample_plugin) on installation, but the monkey patch in `__init__.py` is not working after the plugin is installed via pip. It works in the tests though. I'm sure there's something I'm not understanding about Python internals. It's close though.

**Comment by jmwright** [comment]
I think all of this has been addressed now. The `sampleplugin` readme is a mix of instructions for plugin developers and a sample readme that explains how to install and use the sample plugin. I also switched to using an explicit `register` function in the plugin because there was too much weird implicit magic going on when doing it in `__init__.py`. There is also a sample `setup.py` file in the `sampleplugin` directory that has variables at the top that a developer can modify with their plugin's info.

I think everything should be to the point where a plugin dev could start trying to use this repo.
