### ISSUE TITLE
Use camelCase for plugins functions name

### ISSUE THREAD

**Issue by Jojain** [CadQuery/cadquery-plugins#7]
Looking at what @jmwright wrote for his sample plugin I noticed he didn't used camelCase for his plugin name. Since all cadquery methods are using camelCase I would suggest this being also a standard for plugins functions names so it's consistent with the rest of cadquery, what are your thoughts about it ?

**Comment by jmwright** [comment]
There have been discussions about CadQuery's lack of PEP8 compatibility in function names before. Our stance is that we are not planning to change the function names in the CadQuery repo because it would break too many existing scripts. However, my thought was that this plugins repo could be PEP8 compliant (or at least closer to it) since it doesn't have the historical baggage.

This is certainly a discussion we can have though. Consistency with the existing CadQuery codebase is nice, but so is consistency with the Python community's conventions. We need to decide which is more important to us.

**Comment by Jojain** [comment]
My opinion is that consistency prevails on PEP8. So I would rather have everything camelCase rather than PEP8 accordance.
But either way it would be nice to decide this quickly so it could be added in the contrib specifications

**Comment by jmwright** [comment]
@adam-urbanczyk @marcus7070 @dcowden Please chime in of you have an opinion.

**Comment by adam-urbanczyk** [comment]
I would not enforce it.

**Comment by marcus7070** [comment]
I don't think we should enforce anything here. 

Pros of enforcing camel case:
* consistency with CQ

Cons:
* excessively strict guidelines could be offputting to potential contributors
* reviews would take longer
* greater chance of embarrassing myself when I make a PR with the wrong naming convention

**Comment by jmwright** [comment]
A comment has been added in #8 explaining the history of camelCase, but not forcing users to go that route if they want their code to be compliant with PEP8. Third bullet point [here](https://github.com/CadQuery/cadquery-plugins/blob/676ebb69e3375fff8f2606cd6f131c98d97f8171/README.md#considerations).
